name: pt_architecture
description: Clean Architecture with RxDart and MVVM.
version: 1.0.0+1
homepage: https://github.com/tienpx-x/pt_architecture

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: